language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=null
  - DATABASE_MIGRATIONS_DIR=null
  - DATABASE_MIGRATIONS_TABLE=null
  - SECRET_PATH=null
  # NPM_CONFIG_REGISTRY=???
  - secure: "M6lTv1SEH2nCP5G+C8aUzn6TIlTJltOIkKT50rBN/7aojM91lGcM8wVAiXMtJerxCXPcsNgjQBuGPUSk2lUoCFPuXB3ZQDdEcKZAyvK7GTNDCucciBo7/bH8zJxwbVNeRPmu8diaWhWpA073n2SEma/3TG7DR7s+GOsEmt3ssitqNOFfq1cBg3oEvzxrRvOa7bK1q9b00BKqnufEtpkdOo3Slynw3UIzsaWSAnvA4dLrsK+zewX1pCgMFo/s9/WUn2OU3yK2+ErlmAKq/wbe3gNBbFMCvJZB3zKB1oD3bbd6I0FH038UHEngVeh+6WLT2Tgg3br86hu+hWgE4h/RJLAp/aGqkVsPxxG3ItLapgWw6hITLajzzyVDWTBmprS4aYqrTLgc4j3NgQEvno7g57SyhGUycY57jG3NI8AEgCGzuah3fHLzUiax0vhMC55xo7W3ujRLxe2A9WU/+TTKXS2Kkp+IDcd+7ecW5c7zbgD8oE8ElTK7wE2QViKjDGfY0BaSQldi7XiRB6ISBO3SlkQWbqkeBJcGRTGf0zJmhmMCEZ1lnD8qs96irCd4MeB3oicQ+bO/sbbJzWG3ol2AvfFUk9DTbhDRu+Rhyyk93wBeCcpTg9LU/v2wKxH/ljlZJViVEWciVw+k/17PlJhLA+cFKwCPTSKbr6YBWttt24g="

install:
- npm install --registry=${NPM_CONFIG_REGISTRY} --progress=false

script:
- npm run test-with-coverage

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: bin/togemfury.sh
- provider: heroku
  skip_cleanup: true
  app: identity-staging-neoncity
  api_key:
    secure: "tzTHBD7qPQbH3HEON5iJjBSPm38M7PZdIEK8UBBqMqHk8yYA/LfU8cKB1h39cBXzWgPmAYT27Jb3kuwjOkrUT0nQ19vQk7JCGMgUKqfPGHm3a01doQCFdI/pUjgLQHkTXuQMUcW2Y+r83pJrIl3hvRAEjQ6ITczPXv6M6VlSdMF+3WLie6RQ34bagX0j4GrDM2UU8doLycTXWvO1NcX/yXpGh2j4cdzO6MT9tKln0i0hzjW9Z+QcfPae+rSyoLTnKlc8JlN/OvC9H2gePAsbPwGOugh99/EqkUWzGb6pVX0UajTk6H45RBS3ilQUCDzxWr6vLui5GUi46b4N14Rmxo15qm1xRN3yI5OMDCpNUyNJnqzUU7/1lupbZKz2TYXCz2r+pTpZXR1+EMQmxEpkbup++0RNRTeKz3pDcLqrDcSC3c/giqKyeQzWxs+IJUTGhLbeF3Ck2FSXGRu3mvhHLMELSHvw0dTYA0hzAmsj9OO4FuCjsxHL6B56S2yxd07rETEUEwlgtOrYA9XA6MyS91Oxe96nKv55k7bqtftNiKDcM8yPeTYW6+F92gr1vJF1lxBwsIAVA5iKe6Aby6pWCIsSV5EdqxKXLM47eZ2DSRsW0oxVeW4yANOJtzcCNk9c41aoSYKiluabmXn8Hl2kW+TWNeuYpcBPMZGRDDiDcBs="