language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - SECRET_PATH=null

install:
- npm install --registry=https://npm-proxy.fury.io/vsRAKKMwEs5p1RhfMGiF/neoncity/ --progress=false

script:
- npm run test-with-coverage

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: bin/togemfury.sh
- provider: heroku
  skip_cleanup: true
  app: identity-dev-neoncity
  api_key:
    secure: "tzTHBD7qPQbH3HEON5iJjBSPm38M7PZdIEK8UBBqMqHk8yYA/LfU8cKB1h39cBXzWgPmAYT27Jb3kuwjOkrUT0nQ19vQk7JCGMgUKqfPGHm3a01doQCFdI/pUjgLQHkTXuQMUcW2Y+r83pJrIl3hvRAEjQ6ITczPXv6M6VlSdMF+3WLie6RQ34bagX0j4GrDM2UU8doLycTXWvO1NcX/yXpGh2j4cdzO6MT9tKln0i0hzjW9Z+QcfPae+rSyoLTnKlc8JlN/OvC9H2gePAsbPwGOugh99/EqkUWzGb6pVX0UajTk6H45RBS3ilQUCDzxWr6vLui5GUi46b4N14Rmxo15qm1xRN3yI5OMDCpNUyNJnqzUU7/1lupbZKz2TYXCz2r+pTpZXR1+EMQmxEpkbup++0RNRTeKz3pDcLqrDcSC3c/giqKyeQzWxs+IJUTGhLbeF3Ck2FSXGRu3mvhHLMELSHvw0dTYA0hzAmsj9OO4FuCjsxHL6B56S2yxd07rETEUEwlgtOrYA9XA6MyS91Oxe96nKv55k7bqtftNiKDcM8yPeTYW6+F92gr1vJF1lxBwsIAVA5iKe6Aby6pWCIsSV5EdqxKXLM47eZ2DSRsW0oxVeW4yANOJtzcCNk9c41aoSYKiluabmXn8Hl2kW+TWNeuYpcBPMZGRDDiDcBs="