language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=null
  - DATABASE_MIGRATIONS_DIR=null
  - DATABASE_MIGRATIONS_TABLE=null
  - SECRET_PATH=null
  - CLIENTS=null
  - AUTH0_CLIENT_ID=null
  - AUTH0_DOMAIN=null
  - GEMFURY_USER=neoncity
  # GEMFURY_API_KEY=???
  - secure: "EzbAUoZFAAiT5v0Ky4FuKE+SMjqqJravCHgB3WMjw//gvRedKFSqn9axvijBVFJb+NEfW2CguC0gNnYVKljxYh/6ADp0+hbkkqnIp4okPaJhWQqjado9DrFF4eFSLR3p9KBTyhQxGcQxmXV3+7pThM3NfyGUySfT+NOEOi7/eVYd6EfCg+EUBGeezvGgVEKYQ1xNAVMVvV2iezl/P8kERJht+p47VS58Q7G8bAi1rJ3hNq57VYZmSMnYUdJLKVBxHCtT0WF73JgJdEgxG/A3dPiMEK8WEahfXAQtHI5H7PAG7+/wUmm24RITTzxJMILchTBsfXXbeCP7fLqxGtZeKVmfuti5+auvJAIKid3nFm3klqnf1YhkznXYz6WLsD3f/M3OVpB6M9oKPHxrbE2ujHT/8Lxa7XCLc4iYqyx/hu0NbQjv83e1HTzh5Fme084QuKQ+GLxTbkb5LmGeI9wbzKN4iJWJWyNwBRa5PDj+AHY8npRjT2+RlLbq2f+zuuDIEKju58idMnCrzRxJDrLf6/RTgtycr5IZ+IwwZSBZTFp9FFakMyV/O0rl1xDmZi858WVn/BW4EaST7yOtaxmk5K83MjcqTzCo6PRBaY3BLi4idX2OF+B419/ILNSDkKzV/3VTdpxtrbJIjbvJCk6gueCok7ZxlKrpLdUU0jImk4Y="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
- provider: heroku
  skip_cleanup: true
  app: identity-staging-neoncity
  api_key:
    secure: "tzTHBD7qPQbH3HEON5iJjBSPm38M7PZdIEK8UBBqMqHk8yYA/LfU8cKB1h39cBXzWgPmAYT27Jb3kuwjOkrUT0nQ19vQk7JCGMgUKqfPGHm3a01doQCFdI/pUjgLQHkTXuQMUcW2Y+r83pJrIl3hvRAEjQ6ITczPXv6M6VlSdMF+3WLie6RQ34bagX0j4GrDM2UU8doLycTXWvO1NcX/yXpGh2j4cdzO6MT9tKln0i0hzjW9Z+QcfPae+rSyoLTnKlc8JlN/OvC9H2gePAsbPwGOugh99/EqkUWzGb6pVX0UajTk6H45RBS3ilQUCDzxWr6vLui5GUi46b4N14Rmxo15qm1xRN3yI5OMDCpNUyNJnqzUU7/1lupbZKz2TYXCz2r+pTpZXR1+EMQmxEpkbup++0RNRTeKz3pDcLqrDcSC3c/giqKyeQzWxs+IJUTGhLbeF3Ck2FSXGRu3mvhHLMELSHvw0dTYA0hzAmsj9OO4FuCjsxHL6B56S2yxd07rETEUEwlgtOrYA9XA6MyS91Oxe96nKv55k7bqtftNiKDcM8yPeTYW6+F92gr1vJF1lxBwsIAVA5iKe6Aby6pWCIsSV5EdqxKXLM47eZ2DSRsW0oxVeW4yANOJtzcCNk9c41aoSYKiluabmXn8Hl2kW+TWNeuYpcBPMZGRDDiDcBs="
